# Menu-Sidebar
menu:
  首页:
    path: /
    icon: ico/navbar/home.svg
    submenu: false
  归档:
    path: /archives/
    icon: ico/navbar/archive.svg
    submenu: 
      '技术': {path: /archives/tech/ ,type: page, icon: 'far fa-lightbulb'}
      '杂谈': {path: /archives/sth/ ,type: page, icon: 'fas fa-pen'}
      '笔记': {path: /archives/note/ ,type: page, icon: 'far fa-note-sticky'}
  Lists:
    path: 
    icon: ico/navbar/list.svg
    submenu: 
      '番组': {path: /lists/bangumi/ ,type: page, icon: 'fas fa-tv'}
      '音乐': {path: /lists/music/ ,type: page, icon: 'far fa-headphones'}
      '书架': {path: /lists/books/ ,type: page, icon: 'far fa-bookmark'}
  Friends: 
    path: /friends/
    icon: ico/navbar/heart.svg
    submenu: false
  Project:
    path: 
    icon: ico/navbar/coffee.svg
    submenu: 
      'Nemophila': {path: https://github.com/imouup/Nemophila ,type: link}

rss:
    path: /atom.xml
    icon: ico/navbar/rss.svg

contact:
  'Github': {path: https://github.com/imouup ,icon: /ico/contact/github.svg}
  'Twitter': {path: https://x.com/iznyaku ,icon: /ico/contact/twitter.svg}
  'Bilibili': {path: https://space.bilibili.com/438518095 ,icon: /ico/contact/bilibili.svg}
  'Email': {path: mailto:iznyaku@outlook.com, icon: far fa-envelope}

aboutme:
  path: /about/
  avatar: images/avatar.jpg

tweet:
  api: ''

banner: "images/banner_sky.jpg"

# Content
excerpt_link: Read More
fancybox: true

# # Footer
# copyright: |-
#   <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a></br>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></br>

# Footer
copyright:
# Need help choosing? Please see...
# https://creativecommons.org/choose/
# https://choosealicense.com/
# You can use html like below...
# copyright: |-
#   <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a></br>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></br>

# Sidebar
sidebar: right
widgets:
- tag
- recent_posts
- category
- archive
#- tagcloud



# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# Widget behavior
archive_type: 'monthly'
show_count: false
recent_posts_limits: 5

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
fb_admins:
fb_app_id:

# valine comment system. https://valine.js.org
valine:
  enable: false # if you want use valine,please set this value is true
  appId:  # leancloud application app id
  appKey:  # leancloud application app key
  notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  pageSize: 10 # comment list page size
  avatar: mm # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info
