title: 

# Nav bar
menu:
  首页:
    path: /
    icon: ico/navbar/home.svg
    submenu: false
  归档:
    path: /archives/
    icon: ico/navbar/archive.svg
    submenu: 
      '技术': {path: /archives/tech/ ,type: page, icon: 'far fa-lightbulb'}
      '杂谈': {path: /archives/sth/ ,type: page, icon: 'fas fa-pen'}
      '笔记': {path: /archives/note/ ,type: page, icon: 'far fa-note-sticky'}
  Lists:
    path: 
    icon: ico/navbar/list.svg
    submenu: 
      '番组': {path: /lists/bangumi/ ,type: page, icon: 'fas fa-tv'}
      '音乐': {path: /music/ ,type: page, icon: 'far fa-headphones'}
      '书架': {path: /lists/books/ ,type: page, icon: 'far fa-bookmark'}
  Friends: 
    path: /friends/
    icon: ico/navbar/heart.svg
    submenu: false
  Project:
    path: 
    icon: ico/navbar/coffee.svg
    submenu: 
      'Nemophila': {path: https://github.com/imouup/Nemophila ,type: link}

rss:
    path: /atom.xml
    icon: ico/navbar/rss.svg

contact:
  'Github': {uid: 'imouup',path: 'https://github.com/imouup' ,icon: '/ico/contact/github.svg'}
  'Twitter': {uid: '@iznyaku',path: 'https://x.com/iznyaku' ,icon: '/ico/contact/twitter.svg'}
  'Bilibili': {uid: '438518095' ,path: 'https://space.bilibili.com/438518095' ,icon: '/ico/contact/bilibili.svg'}
  'Email': {uid: 'iznyaku@outlook.com' ,path: 'mailto:iznyaku@outlook.com', icon: far fa-envelope}

aboutme:
  path: /about/
  avatar: images/avatar.jpg

tweet:
  api: 'https://tweet-api-blog.nyaku.moe/tweet'

banner: "images/banner_sky.jpg"

lazyload:
  enable: true
  loading_img: /images/yachiyo_loading2_640.webp

icp_license: 
  icp_license_link: "https://icp.gov.moe/?keyword=20212022"
  text: "萌ICP备20212022号"

back_to_top_img: images/yachiyo.PNG 

cclicense:
  enable: true
  type: "知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议"  # 说明文字，例如：知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议
  url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"  # 许可证链接，例如：https://creativecommons.org/licenses/by-nc-sa/4.0/


waline:
  enable: true
  serverURL: 'https://waline-test.mouup.top' 

# markdown parser
markdown_it_plus:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - plugin:
        name: markdown-it-katex
        enable: true
    - plugin:
        name: markdown-it-mark
        enable: true

# rss
feed:
  type: atom           
  path: atom.xml       
  limit: 0           
  hub:                 # PubSubHubbub协议中心
  content: true        # 是否在RS 中包含文章全文
  content_limit: 140   # 摘要的字符限制
  content_limit_delim: ' ' 
  order_by: -date      # 按日期倒序
  icon: ico/Nemo.svg       # 自定义Feed图标
  autodiscovery: true  